# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "qc_benchmark"
description: Quality control benchmarking and metrics
keywords:
  - nanopore
  - oxford nanopore
  - sequencing
authors:
  - "@foi-bioinformatics"
output:
  - benchmark_results:
      type: file
      description: All benchmark results combined
      pattern: "*.{fastq,fastq.gz,json,txt}"
  - nanoplot_reports:
      type: file
      description: NanoPlot HTML reports
      pattern: "*.html"
  - versions:
      type: file
      description: Software versions
      pattern: "versions.yml"
components: []
