repository_type: pipeline

nf_core_version: 3.3.2

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - LICENSE
    - assets/nf-core-nanometanf_logo_light.png
    - docs/images/nf-core-nanometanf_logo_light.png
    - docs/images/nf-core-nanometanf_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nanometanf_logo_light.png
    - docs/images/nf-core-nanometanf_logo_light.png
    - docs/images/nf-core-nanometanf_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: foi-bioinformatics
  name: nanometanf
  description: Backend of Nanometa-Live
  author: "Andreas Sj\xF6din"
  version: 1.3.1dev
  force: true
  outdir: .
  skip_features:
    - gpu
  is_nfcore: false
