# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "dynamic_resource_allocation"
description: ML-based dynamic resource prediction and optimization
keywords:
  - nanopore
  - oxford nanopore
  - sequencing
components: []
