# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "barcode_discovery"
description: Automatic discovery of pre-demultiplexed barcode directories
keywords:
  - nanopore
  - oxford nanopore
  - sequencing
authors:
  - "@foi-bioinformatics"
output:
  - samples:
      type: file
      description: Discovered barcode samples with metadata
      pattern: "*.{fastq,fastq.gz,fq,fq.gz}"
  - versions:
      type: file
      description: Software versions
      pattern: "versions.yml"
components: []
