# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "taxonomic_classification"
description: Kraken2-based taxonomic profiling
keywords:
  - nanopore
  - oxford nanopore
  - sequencing
components: []
