# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "assembly"
description: De novo assembly of Oxford Nanopore reads
keywords:
  - nanopore
  - oxford nanopore
  - sequencing
authors:
  - "@foi-bioinformatics"
output:
  - assembly:
      type: file
      description: Main assembly FASTA file
      pattern: "*.{fasta.gz,fa.gz}"
  - assembly_graph:
      type: file
      description: Assembly graph in GFA format
      pattern: "*.gfa.gz"
  - assembly_info:
      type: file
      description: Assembly statistics text file
      pattern: "*.txt"
  - assembler_used:
      type: string
      description: Name of the assembler used
  - versions:
      type: file
      description: Software versions
      pattern: "versions.yml"
components: []
