# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "dorado_basecalling"
description: POD5 basecalling using Dorado with quality filtering
keywords:
  - nanopore
  - oxford nanopore
  - sequencing
authors:
  - "@foi-bioinformatics"
output:
  - fastq:
      type: file
      description: Basecalled FASTQ files
      pattern: "*.{fastq,fastq.gz}"
  - summary:
      type: file
      description: Basecalling summary files
      pattern: "*.txt"
  - versions:
      type: file
      description: Software versions
      pattern: "versions.yml"
components: []
