name: "dorado_demux"
description: Demultiplexing of barcoded nanopore sequencing data using Dorado
keywords:
  - demultiplexing
  - nanopore
  - dorado
  - barcodes
  - ont
tools:
  - dorado:
      description: Dorado is a high-performance, easy-to-use, open source basecaller for Oxford Nanopore reads
      homepage: https://github.com/nanoporetech/dorado
      documentation: https://github.com/nanoporetech/dorado
      tool_dev_url: https://github.com/nanoporetech/dorado
      licence: ["Oxford Nanopore Technologies PLC. Public License Version 1.0"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: Basecalled FASTQ file to be demultiplexed
      pattern: "*.fastq{,.gz}"
  - barcode_kit:
      type: string
      description: Barcode kit name (e.g., 'SQK-NBD114-24', 'SQK-RPB004')

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - demuxed_reads:
      type: file
      description: Demultiplexed reads in FASTQ format, organized by barcode directories
      pattern: "demux_output/barcode*/*.fastq*"
  - unclassified:
      type: file
      description: Unclassified reads that could not be assigned to barcodes
      pattern: "demux_output/unclassified/*.fastq*"
  - summary:
      type: file
      description: Summary of demultiplexing run
      pattern: "demux_output/demux_summary.txt"

authors:
  - "@andreassjodin"