# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "qc_analysis"
description: Comprehensive quality control with FASTP and NanoPlot
keywords:
  - nanopore
  - oxford nanopore
  - sequencing
authors:
  - "@foi-bioinformatics"
components: []
