# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "enhanced_realtime_monitoring"
description: Real-time file monitoring with statistics generation
keywords:
  - nanopore
  - oxford nanopore
  - sequencing
components: []
