# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "validation"
description: BLAST-based validation for targeted species confirmation
keywords:
  - nanopore
  - oxford nanopore
  - sequencing
authors:
  - "@foi-bioinformatics"
output:
  - txt:
      type: file
      description: BLAST validation results
      pattern: "*.txt"
  - versions:
      type: file
      description: Software versions
      pattern: "versions.yml"
components: []
