# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "validation"
description: BLAST-based validation for targeted species confirmation
keywords:
  - nanopore
  - oxford nanopore
  - sequencing
components: []
