name: nf-test

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run nf-test (stub)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "25.10.0"

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          version: "0.9.2"

      - name: Run nf-test
        run: nf-test test --profile test
